/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./modules/shared/components/AppFooter.vue')['default']
    AppHeader: typeof import('./modules/shared/components/AppHeader.vue')['default']
    AppModal: typeof import('./modules/shared/components/AppModal.vue')['default']
    AppNavigation: typeof import('./modules/shared/components/AppNavigation.vue')['default']
    CartItem: typeof import('./modules/job-change/components/CartItem.vue')['default']
    FeatureCard: typeof import('./modules/shared/components/FeatureCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HelpModal: typeof import('./modules/pet-evaluate/components/HelpModal.vue')['default']
    HelpTabs: typeof import('./modules/shared/components/HelpTabs.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    JobChangeCalculator: typeof import('./modules/job-change/components/JobChangeCalculator.vue')['default']
    LanguageSwitcher: typeof import('./modules/shared/components/LanguageSwitcher.vue')['default']
    PetEvaluateMain: typeof import('./modules/pet-evaluate/components/PetEvaluateMain.vue')['default']
    PetResultDisplay: typeof import('./modules/pet-evaluate/components/PetResultDisplay.vue')['default']
    PetSelector: typeof import('./modules/pet-evaluate/components/PetSelector.vue')['default']
    PetSkillSelector: typeof import('./modules/pet-evaluate/components/PetSkillSelector.vue')['default']
    PetStatsInput: typeof import('./modules/pet-evaluate/components/PetStatsInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
